---
abstract: 'a pure-Perl implementation of the RIPE Database client.'
author:
  - 'Luis Motta Campos <lmc@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1002, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Whois-RIPE
no_index:
  directory:
    - t
    - inc
recommends:
  LWP::UserAgent: '0'
requires:
  Iterator: '0'
  Test::More: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/arhuman/Net-Whois-RIPE/issues
  repository: https://github.com/arhuman/Net-Whois-RIPE
version: 2.007001
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
