---
abstract: 'a pure-Perl implementation of the RIPE Database client.'
author:
  - 'Luis Motta Campos <lmc@cpan.org>'
build_requires:
  Test::Exception: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Whois-RIPE
no_index:
  directory:
    - t
    - inc
requires:
  Iterator: 0
  Iterator::Util: 0
  Test::More: 0
  perl: 5.006
version: 2.00_010
